In [19]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

Data cleanup

In [20]:
data = pd.read_csv('data/data.csv')
data

,user_id,country,age,year,internet_penetration,mental_health_support_index,gdp_index,youth_population_ratio,baseline_addiction_pressure,tiktok_minutes_daily,...,addiction_pressure,attention_span_score,dopamine_dependency_score,impulsivity_index,sleep_hours,sleep_quality_index,ASI,MHRI,addiction_score,addiction_level
0,1,Philippines,59,2050,88.895513,64.347080,0.312067,0.310389,64.762693,242.853130,...,69.981792,77.479304,27.024835,60.044856,6.561778,7.912360,100.0,40.460626,63.512418,High
1,2,Netherlands,23,2035,57.950292,76.257045,0.460320,0.293134,37.592646,98.599951,...,56.862382,78.852713,25.376744,81.769114,9.400197,2.292106,100.0,79.424028,62.688372,High
2,3,Laos,26,2060,40.325805,55.846514,0.893658,0.183055,22.589595,127.221573,...,41.817693,83.573012,19.712386,99.613065,7.810417,2.308761,100.0,88.262729,59.856193,High
3,4,Bulgaria,50,2046,43.838044,28.390576,0.661523,0.155038,57.093084,140.528514,...,70.811984,83.437675,19.874790,86.935944,7.020033,4.512440,100.0,70.905771,59.937395,High
4,5,Zambia,24,2045,43.749943,81.413755,0.275186,0.457115,57.653485,187.748696,...,71.990949,71.993561,33.607727,45.275020,7.900621,4.265014,100.0,51.312439,66.803864,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,Cambodia,30,2019,88.112224,35.854704,0.930592,0.389052,73.468587,138.532061,...,88.124399,87.352146,15.177425,68.300175,7.762866,4.137675,100.0,63.461711,57.588712,High
9996,9997,Nepal,44,2021,75.276099,88.995532,0.335594,0.174699,26.671849,109.827675,...,34.390640,84.661070,18.406715,24.921506,6.227259,6.912484,100.0,27.898335,59.203358,High
9997,9998,Brazil,44,2039,75.320851,55.599948,0.918843,0.373100,69.587448,157.642548,...,73.780044,77.524906,26.970113,46.063910,8.612393,8.322962,100.0,31.417147,63.485057,High
9998,9999,Iceland,57,2022,41.499728,82.096050,0.698312,0.412805,78.463688,89.940360,...,79.496451,83.099185,20.280978,80.615419,4.786482,9.586895,100.0,42.373235,60.140489,High
9999,10000,Bolivia,48,2048,81.776282,25.388594,0.328646,0.244791,25.477201,96.210561,...,40.584723,85.108617,17.869659,70.945695,7.560006,3.956991,100.0,65.687893,58.934830,High

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   user_id                      10000 non-null  int64
 1   country                      10000 non-null  object
 2   age                          10000 non-null  int64
 3   year                         10000 non-null  int64
 4   internet_penetration         10000 non-null  float64
 5   mental_health_support_index  10000 non-null  float64
 6   gdp_index                    10000 non-null  float64
 7   youth_population_ratio       10000 non-null  float64
 8   baseline_addiction_pressure  10000 non-null  float64
 9   tiktok_minutes_daily         10000 non-null  float64
 10  instagram_minutes_daily      10000 non-null  float64
 11  night_usage_ratio            10000 non-null  float64
 12  scroll_velocity              10000 non-null  float64
 13  addiction_pressure           10000 non-null  float64
 14  attention_span_score         10000 non-null  float64
 15  dopamine_dependency_score    10000 non-null  float64
 16  impulsivity_index            10000 non-null  float64
 17  sleep_hours                  10000 non-null  float64
 18  sleep_quality_index          10000 non-null  float64
 19  ASI                          10000 non-null  float64
 20  MHRI                         10000 non-null  float64
 21  addiction_score              10000 non-null  float64
 22  addiction_level              10000 non-null  object
dtypes: float64(18), int64(3), object(2)
memory usage: 1.8+ MB

In [ ]:
data.shape[0]

10000

In [25]:
data.isna().sum()

user_id                        0
country                        0
age                            0
year                           0
internet_penetration           0
mental_health_support_index    0
gdp_index                      0
youth_population_ratio         0
baseline_addiction_pressure    0
tiktok_minutes_daily           0
instagram_minutes_daily        0
night_usage_ratio              0
scroll_velocity                0
addiction_pressure             0
attention_span_score           0
dopamine_dependency_score      0
impulsivity_index              0
sleep_hours                    0
sleep_quality_index            0
ASI                            0
MHRI                           0
addiction_score                0
addiction_level                0
dtype: int64

In [ ]:
data = data.drop_duplicates()

In [40]:
data = data.drop(data[data['year'] > 2026].index)
data.head()

,user_id,country,age,year,internet_penetration,mental_health_support_index,gdp_index,youth_population_ratio,baseline_addiction_pressure,tiktok_minutes_daily,...,addiction_pressure,attention_span_score,dopamine_dependency_score,impulsivity_index,sleep_hours,sleep_quality_index,ASI,MHRI,addiction_score,addiction_level
18,19,China,46,2018,94.390580,36.943869,0.645441,0.374847,49.557506,58.792207,...,58.024148,86.402902,16.316518,32.436500,7.298723,6.613343,98.515875,33.151534,57.416196,High
19,20,Czechia,43,2025,42.740574,55.752311,0.704911,0.236706,27.024021,136.855216,...,34.913731,81.163815,22.603422,99.239768,8.095954,6.844116,100.000000,65.399305,61.301711,High
23,24,Belgium,42,2016,70.960629,33.059904,0.797193,0.210653,39.719873,17.959560,...,51.533919,88.551882,13.737742,25.943267,4.656685,5.274382,92.316799,36.599725,53.027271,High
31,32,Mozambique,15,2021,59.185816,66.198883,0.228754,0.431218,74.069481,120.175304,...,86.746832,87.301791,15.237851,57.658179,6.462717,4.929060,100.000000,54.183792,57.618926,High
33,34,Greece,34,2021,51.780753,77.261034,0.978408,0.344024,46.491830,34.378532,...,53.980710,91.484832,10.218201,66.078848,6.646852,7.004448,66.068766,48.017183,38.143484,Medium

Data transformation

In [43]:
columns = ['user_id', 'age', 'year', 'tiktok_minutes_daily', 'instagram_minutes_daily', 'sleep_hours', 'addiction_score']
data2 = data[columns].copy()
data2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2621 entries, 18 to 9998
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  2621 non-null   int64
 1   age                      2621 non-null   int64
 2   year                     2621 non-null   int64
 3   tiktok_minutes_daily     2621 non-null   float64
 4   instagram_minutes_daily  2621 non-null   float64
 5   sleep_hours              2621 non-null   float64
 6   addiction_score          2621 non-null   float64
dtypes: float64(4), int64(3)
memory usage: 163.8 KB

In [44]:
data2['total_minutes_daily'] = data2['tiktok_minutes_daily'] + data2['instagram_minutes_daily']

In [54]:
data2['sos_situation'] = ((data2['total_minutes_daily'] / 60) > 3).astype(int)

In [55]:
data2['covid'] = data2['year'].apply(lambda x: 1 if 2022 >=x >= 2020 else 0)

In [56]:
data2

,user_id,age,year,tiktok_minutes_daily,instagram_minutes_daily,sleep_hours,addiction_score,total_minutes_daily,sos_situation,covid
18,19,46,2018,58.792207,104.372974,7.298723,57.416196,163.165180,0,0
19,20,43,2025,136.855216,89.179008,8.095954,61.301711,226.034224,1,0
23,24,42,2016,17.959560,119.417856,4.656685,53.027271,137.377416,0,0
31,32,15,2021,120.175304,32.203208,6.462717,57.618926,152.378512,0,1
33,34,34,2021,34.378532,67.803482,6.646852,38.143484,102.182015,0,1
...,...,...,...,...,...,...,...,...,...,...
9988,9989,57,2018,102.116148,217.361252,6.414216,65.973870,319.477400,1,0
9989,9990,21,2015,142.742400,150.664773,7.696633,64.670359,293.407174,1,0
9995,9996,30,2019,138.532061,13.242186,7.762866,57.588712,151.774246,0,0
9996,9997,44,2021,109.827675,74.239479,6.227259,59.203358,184.067154,1,1
9998,9999,57,2022,89.940360,112.869419,4.786482,60.140489,202.809779,1,1

In [58]:
data2.describe()

,user_id,age,year,tiktok_minutes_daily,instagram_minutes_daily,sleep_hours,addiction_score,total_minutes_daily,sos_situation,covid
count,2621.000000,2621.000000,2621.000000,2621.000000,2621.000000,2621.000000,2621.000000,2621.000000,2621.000000,2621.000000
mean,5007.758871,35.532621,2020.629912,119.479992,100.598992,7.009292,58.535584,220.078983,0.700878,0.254101
std,2887.986676,13.388990,3.449915,57.887198,49.458432,1.481694,9.208167,75.320234,0.457961,0.435438
min,19.000000,13.000000,2015.000000,0.000000,0.000000,3.000000,5.889972,0.000000,0.000000,0.000000
25%,2514.000000,24.000000,2018.000000,80.482906,67.156795,6.005609,58.098778,169.270398,0.000000,0.000000
50%,4999.000000,35.000000,2021.000000,118.873065,100.001809,6.984021,60.958964,219.179278,1.000000,0.000000
75%,7560.000000,47.000000,2024.000000,159.501140,133.794061,8.062127,63.680905,273.618093,1.000000,1.000000
max,9999.000000,59.000000,2026.000000,335.320877,272.527739,10.000000,74.607130,492.142605,1.000000,1.000000